version: '3.8'

services:


    mysqltest:
      image: mysql:latest
      environment:
        - MYSQL_ROOT_PASSWORD=lucasvieira
        
      ports:
        - 3306:3306
        
        
    volumes:
	- mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql
        
        
        
volumes:
    mysqlVolume:
    mysqlConfig:
